export enum FlagType {
    Player = "Player",
    Eggs = "EggFlags",
    FerretFruit = "FerretFruit",
    FoxBerry = "FoxBerry",
    HairExtensionSerum = "HairExtensionSerum",
    MinotaurCum = "MinotaurCum",
    PhoukaWhiskey = "PhoukaWhiskey",
    Reptilum = "Reptilum",
    DragonShellShield = "DragonShellShield",
    Valeria = "Valeria",
    LustyMaidensArmor = "LustyMaidensArmor",
    Ceraph = "Ceraph",
    Raphael = "Raphael",
    BeeGirl = "BeeGirl",
    Jojo = "Jojo",
    Exgartuan = "Exgartuan",
    CeruleanSuccubus = "CeruleanSuccubus",
    CeruleanPotion = "CeruleanPotion",
    SophieScene = "SophieScene"
}
