export enum EffectType {
    // Status Effects

    // Non-combat player perks
    AllNaturalOnaholeUsed = "AllNaturalOnaholeUsed",
    AteEgg = "AteEgg",
    AnemoneArousal = "AnemoneArousal",
    BimboChampagne = "BimboChampagne",
    Birthed = "Birthed",
    BirthedImps = "BirthedImps",
    BlackCatBeer = "BlackCatBeer",
    BlackNipples = "BlackNipples",
    BlowjobOn = "BlowjobOn",
    BoatDiscovery = "BoatDiscovery",
    BonusACapacity = "BonusACapacity",
    BonusVCapacity = "BonusVCapacity",
    BottledMilk = "BottledMilk",
    BreastsMilked = "BreastsMilked",
    BSwordBroken = "BSwordBroken",
    BuiltMilker = "BuiltMilker",
    BurpChanged = "BurpChanged",
    ButtStretched = "ButtStretched",
    CampAnemoneTrigger = "CampAnemoneTrigger",
    CampMarble = "CampMarble",
    CampRathazul = "CampRathazul",
    ClaraCombatRounds = "ClaraCombatRounds",
    ClaraFoughtInCamp = "ClaraFoughtInCamp",
    CockPumped = "CockPumped",
    Contraceptives = "Contraceptives",
    CuntStretched = "CuntStretched",
    DefenseCanopy = "DefenseCanopy",
    DeluxeOnaholeUsed = "DeluxeOnaholeUsed",
    DogWarning = "DogWarning",
    DragonBreathBoost = "DragonBreathBoost",
    DragonBreathCooldown = "DragonBreathCooldown",
    DungeonShutDown = "DungeonShutDown",
    Dysfunction = "Dysfunction",
    Edryn = "Edryn",
    Eggchest = "Eggchest",
    Eggs = "Eggs",
    EmberFuckCooldown = "EmberFuckCooldown",
    EmberNapping = "EmberNapping",
    EverRapedJojo = "EverRapedJojo",
    Exgartuan = "Exgartuan",
    ExploredDeepwoods = "ExploredDeepwoods",
    FactoryOmnibusDefeated = "FactoryOmnibusDefeated",
    FactoryOverload = "FactoryOverload",
    FactoryIncubusDefeated = "FactoryIncubusDefeated",
    FactorySuccubusDefeated = "FactorySuccubusDefeated",
    FaerieFemFuck = "FaerieFemFuck",
    FaerieFucked = "FaerieFucked",
    FappedGenderless = "FappedGenderless",
    Feeder = "Feeder",
    Fertilized = "Fertilized",
    FetishOn = "FetishOn",
    FoundFactory = "FoundFactory",
    FuckedMarble = "FuckedMarble",
    Goojob = "Goojob",
    GooStuffed = "GooStuffed",
    Groundpound = "Groundpound",
    HairdresserMeeting = "HairdresserMeeting",
    Hangover = "Hangover",
    Heat = "Heat",
    HorseWarning = "HorseWarning",
    ImmolationSpell = "ImmolationSpell",
    ImpGangBang = "ImpGangBang",
    IncubusBribed = "IncubusBribed",
    Infested = "Infested",
    IzmaBlowing = "IzmaBlowing",
    IzumisPipeSmoke = "IzumisPipeSmoke",
    JerkingIzma = "JerkingIzma",
    Jizzpants = "Jizzpants",
    JojoMeditationCount = "JojoMeditationCount",
    JojoNightWatch = "JojoNightWatch",
    JojoTFOffer = "JojoTFOffer",
    Kelt = "Kelt",
    KeltBJ = "KeltBJ",
    KeltBadEndWarning = "KeltBadEndWarning",
    KeltOff = "KeltOff",
    KnowsArouse = "KnowsArouse",
    KnowsBlind = "KnowsBlind",
    KnowsCharge = "KnowsCharge",
    KnowsHeal = "KnowsHeal",
    KnowsMight = "KnowsMight",
    KnowsWhitefire = "KnowsWhitefire",
    LactationEndurance = "LactationEndurance",
    LactationReduction = "LactationReduction",
    LactationReduc0 = "LactationReduc0",
    LactationReduc1 = "LactationReduc1",
    LactationReduc2 = "LactationReduc2",
    LactationReduc3 = "LactationReduc3",
    LootEgg = "LootEgg",
    LostVillagerSpecial = "LostVillagerSpecial",
    LustStick = "LustStick",
    LustStickApplied = "LustStickApplied",
    LustyTongue = "LustyTongue",
    MalonVisitedPostAddiction = "MalonVisitedPostAddiction",
    MaraeComplete = "MaraeComplete",
    MaraesLethicite = "MaraesLethicite",
    MaraesQuestStart = "MaraesQuestStart",
    Marble = "Marble",
    MarbleHasItem = "MarbleHasItem",
    MarbleItemCooldown = "MarbleItemCooldown",
    MarbleRapeAttempted = "MarbleRapeAttempted",
    MarblesMilk = "MarblesMilk",
    MarbleSpecials = "MarbleSpecials",
    MarbleWithdrawl = "MarbleWithdrawl",
    Meditated = "Meditated",
    MeanToNaga = "MeanToNaga",
    MeetWanderer = "MeetWanderer",
    MetCorruptMarae = "MetCorruptMarae",
    MetMarae = "MetMarae",
    MetRathazul = "MetRathazul",
    MetWorms = "MetWorms",
    MetWhitney = "MetWhitney",
    Milked = "Milked",
    MinoPlusCowgirl = "MinoPlusCowgirl",
    Naga = "Naga",
    NakedOn = "NakedOn",
    NoJojo = "NoJojo",
    NoMoreMarble = "NoMoreMarble",
    Oswald = "Oswald",
    PlainOnaholeUsed = "PlainOnaholeUsed",
    PhoukaWhiskeyAffect = "PhoukaWhiskeyAffect",
    PostAkbalSubmission = "PostAkbalSubmission",
    PostAnemoneBeatdown = "PostAnemoneBeatdown",
    PureCampJojo = "PureCampJojo",
    RathazulArmor = "RathazulArmor",
    RepeatSuccubi = "RepeatSuccubi",
    Rut = "Rut",
    SharkGirl = "SharkGirl",
    ShieldingSpell = "ShieldingSpell",
    SlimeCraving = "SlimeCraving",
    SlimeCravingFeed = "SlimeCravingFeed",
    SlimeCravingOutput = "SlimeCravingOutput",
    SuccubiFirst = "SuccubiFirst",
    SuccubiNight = "SuccubiNight",
    TakenGroPlus = "TakenGroPlus",
    TakenLactaid = "TakenLactaid",
    // Used only for compatibility with old save files, otherwise no longer in use
    Tamani = "Tamani",
    // Used only for compatibility with old save files, otherwise no longer in use
    TamaniFemaleEncounter = "TamaniFemaleEncounter",
    TelAdre = "TelAdre",
    TentacleBadEndCounter = "TentacleBadEndCounter",
    TentacleJojo = "TentacleJojo",
    TensionReleased = "TensionReleased",
    TF2 = "TF2",
    TookBlessedSword = "TookBlessedSword",
    /**
     * v1 = bonus index
     * v2 = bonus value
     * v3 = remaining time
     */
    UmasMassage = "UmasMassage",
    Uniball = "Uniball",
    UsedNaturalSelfStim = "UsedNaturalSelfStim",
    used_self_dash_stim = "used_self_dash_stim",
    Victoria = "Victoria",
    VoluntaryDemonpack = "VoluntaryDemonpack",
    WormOffer = "WormOffer",
    WormPlugged = "WormPlugged",
    WormsHalf = "WormsHalf",
    WormsOff = "WormsOff",
    WormsOn = "WormsOn",
    WandererDemon = "WandererDemon",
    WandererHuman = "WandererHuman",
    Yara = "Yara",
    CameWorms = "CameWorms",

    // Perks

    // UNSORTED perks TODO these are mostly incorrect perks: tested but never created
    Brawler = "Brawler",
    Buttslut = "Buttslut",
    Focused = "Focused",
    /* Never used, removed because it used a numbered event. Could be re-implemented differently if some new monster actually uses it
    LastStrike = "LastStrike",
    */

    // Player creation perks
    Fast = "Fast",
    Lusty = "Lusty",
    Sensitive = "Sensitive",
    Smart = "Smart",
    Strong = "Strong",
    Tough = "Tough",
    // Female creation perks
    BigClit = "BigClit",
    BigTits = "BigTits",
    Fertile = "Fertile",
    WetPussy = "WetPussy",
    // Male creation perks
    BigCock = "BigCock",
    MessyOrgasms = "MessyOrgasms",

    // History perks
    HistoryAlchemist = "HistoryAlchemist",
    HistoryFighter = "HistoryFighter",
    HistoryHealer = "HistoryHealer",
    HistoryReligious = "HistoryReligious",
    HistoryScholar = "HistoryScholar",
    HistorySlacker = "HistorySlacker",
    HistorySlut = "HistorySlut",
    HistorySmith = "HistorySmith",
    HistoryWhore = "HistoryWhore",

    // Ordinary (levelup) perks
    Acclimation = "Acclimation",
    Agility = "Agility",
    Archmage = "Archmage",
    ArousingAura = "ArousingAura",
    Berzerker = "Berzerker",
    BrutalBlows = "BrutalBlows",
    Channeling = "Channeling",
    CorruptedLibido = "CorruptedLibido",
    DoubleAttack = "DoubleAttack",
    Evade = "Evade",
    FertilityPlus = "FertilityPlus",
    HotBlooded = "HotBlooded",
    ImmovableObject = "ImmovableObject",
    IronMan = "IronMan",
    LightningStrikes = "LightningStrikes",
    LungingAttacks = "LungingAttacks",
    Mage = "Mage",
    Masochist = "Masochist",
    Medicine = "Medicine",
    Nymphomania = "Nymphomania",
    Precision = "Precision",
    Regeneration = "Regeneration",
    Regeneration2 = "Regeneration2",
    Resistance = "Resistance",
    Resolute = "Resolute",
    Runner = "Runner",
    Sadist = "Sadist",
    Seduction = "Seduction",
    SpeedyRecovery = "SpeedyRecovery",
    Spellpower = "Spellpower",
    StrongBack = "StrongBack",
    StrongBack2 = "StrongBack2",
    Tactician = "Tactician",
    Tank = "Tank",
    Tank2 = "Tank2",
    ThunderousStrikes = "ThunderousStrikes",
    WeaponMastery = "WeaponMastery",
    WellAdjusted = "WellAdjusted",

    // Needlework perks
    ChiReflowAttack = "ChiReflowAttack",
    ChiReflowDefense = "ChiReflowDefense",
    ChiReflowLust = "ChiReflowLust",
    ChiReflowMagic = "ChiReflowMagic",
    ChiReflowSpeed = "ChiReflowSpeed",

    // Piercing perks
    PiercedCrimstone = "PiercedCrimstone",
    PiercedFertite = "PiercedFertite",
    PiercedFurrite = "PiercedFurrite",
    PiercedLethite = "PiercedLethite",

    // Cock sock perks
    LustyRegeneration = "LustyRegeneration",
    MidasCock = "MidasCock",
    PentUp = "PentUp",
    PhallicPotential = "PhallicPotential",
    PhallicRestraint = "PhallicRestraint",

    // Armor perks
    BloodMage = "BloodMage",
    SluttySeduction = "SluttySeduction",
    WizardsEndurance = "WizardsEndurance",

    // Weapon perks
    WizardsFocus = "WizardsFocus",

    // Achievement perks
    BroodMother = "BroodMother",
    SpellcastingAffinity = "SpellcastingAffinity",

    // Mutation perks
    Androgyny = "Androgyny",
    BasiliskWomb = "BasiliskWomb",
    BeeOvipositor = "BeeOvipositor",
    BimboBody = "BimboBody",
    BimboBrains = "BimboBrains",
    BroBody = "BroBody",
    BroBrains = "BroBrains",
    BunnyEggs = "BunnyEggs",
    CorruptedNinetails = "CorruptedNinetails",
    Diapause = "Diapause",
    Dragonfire = "Dragonfire",
    EnlightenedNinetails = "EnlightenedNinetails",
    // Feeder = "Feeder",
    Flexibility = "Flexibility",
    FutaFaculties = "FutaFaculties",
    FutaForm = "FutaForm",
    HarpyWomb = "HarpyWomb",
    Incorporeality = "Incorporeality",
    MinotaurCumAddict = "MinotaurCumAddict",
    Oviposition = "Oviposition",
    PurityBlessing = "PurityBlessing",
    SlimeCore = "SlimeCore",
    SpiderOvipositor = "SpiderOvipositor",
    ThickSkin = "ThickSkin",

    // Quest, Event & NPC perks
    BulgeArmor = "BulgeArmor",
    Cornucopia = "Cornucopia",
    ElvenBounty = "ElvenBounty",
    FerasBoonAlpha = "FerasBoonAlpha",
    FerasBoonBreedingBitch = "FerasBoonBreedingBitch",
    FerasBoonMilkingTwat = "FerasBoonMilkingTwat",
    FerasBoonSeeder = "FerasBoonSeeder",
    FerasBoonWideOpen = "FerasBoonWideOpen",
    FireLord = "FireLord",
    Hellfire = "Hellfire",
    LuststickAdapted = "LuststickAdapted",
    MagicalFertility = "MagicalFertility",
    MagicalVirility = "MagicalVirility",
    MaraesGiftButtslut = "MaraesGiftButtslut",
    MaraesGiftFertility = "MaraesGiftFertility",
    MaraesGiftProfractory = "MaraesGiftProfractory",
    MaraesGiftStud = "MaraesGiftStud",
    MarbleResistant = "MarbleResistant",
    // MarblesMilk = "MarblesMilk",
    Misdirection = "Misdirection",
    OmnibusGift = "OmnibusGift",
    OneTrackMind = "OneTrackMind",
    PilgrimsBounty = "PilgrimsBounty",
    PureAndLoving = "PureAndLoving",
    SensualLover = "SensualLover",
    // Whispered = "Whispered",

    ControlledBreath = "ControlledBreath",
    CleansingPalm = "CleansingPalm",
    Enlightened = "Enlightened",

    // Monster perks
    Acid = "Acid",

    // Added
    LustyMaidensArmor = "LustyMaidensArmor",

    // Combat Effects
    // monster
    Attacks = "Attacks",
    BimboBrawl = "BimboBrawl",
    BowCooldown = "BowCooldown",
    BowDisabled = "BowDisabled",
    Charged = "Charged",
    Climbed = "Climbed",
    Concentration = "Concentration",
    Constricted = "Constricted",
    CoonWhip = "CoonWhip",
    Counter = "Counter",
    DomFight = "DomFight",
    DrankMinoCum = "DrankMinoCum",
    DrankMinoCum2 = "DrankMinoCum2",
    Earthshield = "Earthshield",
    Fear = "Fear",
    GenericRunDisabled = "GenericRunDisabled",
    Gigafire = "Gigafire",
    GottaOpenGift = "GottaOpenGift",
    HolliBurning = "HolliBurning",
    Illusion = "Illusion",
    ImpSkip = "ImpSkip",
    ImpUber = "ImpUber",
    JojoIsAssisting = "JojoIsAssisting",
    JojoPyre = "JojoPyre",
    Keen = "Keen",
    Level = "Level",
    KitsuneFight = "KitsuneFight",
    LustAura = "LustAura",
    Milk = "Milk",
    MilkyUrta = "MilkyUrta",
    MinoMilk = "MinoMilk",
    MinotaurEntangled = "MinotaurEntangled",
    MissFirstRound = "MissFirstRound",
    NoLoot = "NoLoot",
    PCTailTangle = "PCTailTangle",
    PeachLootLoss = "PeachLootLoss",
    PhyllaFight = "PhyllaFight",
    Platoon = "Platoon",
    QueenBind = "QueenBind",
    // @aimozg HA HA HA
    Round = "Round",
    RunDisabled = "RunDisabled",
    Shell = "Shell",
    SirenSong = "SirenSong",
    Spar = "Spar",
    Sparring = "Sparring",
    spiderfight = "spiderfight",
    StunCooldown = "StunCooldown",
    TentacleCoolDown = "TentacleCoolDown",
    Timer = "Timer",
    Uber = "Uber",
    UrtaSecondWinded = "UrtaSecondWinded",
    UsedTitsmother = "UsedTitsmother",
    Vala = "Vala",
    Vapula = "Vapula",
    WhipReady = "WhipReady",

    // Player combat affects
    AcidSlap = "AcidSlap",
    AkbalSpeed = "AkbalSpeed",
    AmilyVenom = "AmilyVenom",
    AnemoneVenom = "AnemoneVenom",
    AttackDisabled = "AttackDisabled",
    BasiliskCompulsion = "BasiliskCompulsion",
    BasiliskSlow = "BasiliskSlow",
    Berzerking = "Berzerking",
    Blind = "Blind",
    Bound = "Bound",
    CalledShot = "CalledShot",
    ChargeWeapon = "ChargeWeapon",
    Chokeslam = "Chokeslam",
    Confusion = "Confusion",
    DemonSeed = "DemonSeed",
    Disarmed = "Disarmed",
    DriderKiss = "DriderKiss",
    FirstAttack = "FirstAttack",
    GnollSpear = "GnollSpear",
    GooArmorBind = "GooArmorBind",
    GooArmorSilence = "GooArmorSilence",
    GooBind = "GooBind",
    HarpyBind = "HarpyBind",
    HolliConstrict = "HolliConstrict",
    InfestAttempted = "InfestAttempted",
    IsabellaStunned = "IsabellaStunned",
    IzmaBleed = "IzmaBleed",
    KissOfDeath = "KissOfDeath",
    LustStones = "LustStones",
    lustvenom = "lustvenom",
    Might = "Might",
    NagaBind = "NagaBind",
    NagaVenom = "NagaVenom",
    NoFlee = "NoFlee",
    ParalyzeVenom = "ParalyzeVenom",
    PhysicalDisabled = "PhysicalDisabled",
    Poison = "Poison",
    Sandstorm = "Sandstorm",
    Sealed = "Sealed",
    SheilaOil = "SheilaOil",
    Shielding = "Shielding",
    StoneLust = "StoneLust",
    Stunned = "Stunned",
    TailWhip = "TailWhip",
    TemporaryHeat = "TemporaryHeat",
    TentacleBind = "TentacleBind",
    ThroatPunch = "ThroatPunch",
    Titsmother = "Titsmother",
    TwuWuv = "TwuWuv",
    UBERWEB = "UBERWEB",
    Web = "Web",
    WebSilence = "WebSilence",
    Whispered = "Whispered",

    RemovedArmor = "RemovedArmor",
    JCLustLevel = "JCLustLevel",
    MirroredAttack = "MirroredAttack",
    KnockedBack = "KnockedBack",
    Tentagrappled = "Tentagrappled",
    TentagrappleCooldown = "TentagrappleCooldown",
    ShowerDotEffect = "ShowerDotEffect",
    GardenerSapSpeed = "GardenerSapSpeed",
    VineHealUsed = "VineHealUsed",

    SuccubusAura = "SuccubusAura",
}
