export enum ArmorName {
    ComfortUndercloth = "c.under",
    GreenClothes = "G. Clothes",
    LongDress = "B.Dress",
    BeeArmor = "BeeArmr",
    BimboSkirt = "BimboSk",
    BondageStraps = "BonStrp",
    ComfortClothes = "C.Cloth",
    ChainmailBikini = "Chn Bikini",
    SuitClothes = "ClssyCl",
    FullChainmail = "FullChn",
    FullPlatemail = "FullPlt",
    GelArmor = "GelArmr",
    GooArmor = "GooArmr",
    InquisitorsCorset = "I.Corst",
    InquisitorsRobes = "I.Robes",
    IndecentSteelArmor = "IndecSt",
    LeatherArmor = "LeathrA",
    LeatherArmorSegments = "UrtaLta",
    LustyMaidensArmor = "LMArmor",
    TightLeatherPants = "LthrPnt",
    LeatherRobes = "LthrRob",
    ModestRobes = "M.Robes",
    NurseOutfit = "NurseCl",
    Overalls = "Overall",
    RedBodysuit = "R.BdySt",
    RubberFetishClothes = "RbbrClt",
    SluttySwimwear = "S.Swmwr",
    Scalemail = "ScaleMl",
    SeductiveArmor = "SeductA",
    SpidersilkRobes = "SS.Robe",
    SpidersilkArmor = "SSArmor",
    SemiTransBodysuit = "T.BSuit",
    TubeTop = "TubeTop",
    WizardRobes = "W.Robes",

    FurLoincloth = "FurLoin"
}
