export enum CharacterType {
    Player = "Player",
    Minotaur = "Minotaur",
    MinotaurMob = "MinotaurMob",
    Ceraph = "Ceraph",
    BeeGirl = "BeeGirl",
    Jojo = "Jojo",
    Harpy = "Harpy",
    Sophie = "Sophie",
    Ember = "Ember",
    Kiha = "Kiha",
    Hel = "Hel",
    Isabella = "Isabella",
    Akbal = "Akbal",
    Kitsune = "Kitsune",
    TentacleBeast = "TentacleBeast",
    Imp = "Imp",
    ImpLord = "ImpLord",
    Tamani = "Tamani",
    TamanisDaughters = "TamanisDaughters",
    Goblin = "Goblin",
    ImpGang = "ImpGang"
}
