import { CaninePepperType, CaninePepper } from './Consumables/CaninePepper';
import { EggType, Eggs } from './Consumables/Eggs';
import { HairDyeType, HairDye } from './Consumables/HairDye';
import { BeeHoney } from './Consumables/BeeHoney';
import { BimboLiqueur } from './Consumables/BimboLiqueur';
import { BlackCatBeer } from './Consumables/BlackCatBeer';
import { BlackSpellbook } from './Consumables/BlackSpellbook';
import { BroBrew } from './Consumables/BroBrew';
import { CeruleanPotion } from './Consumables/CeruleanPotion';
import { Coal } from './Consumables/Coal';
import { DeBimbo } from './Consumables/DeBimbo';
import { DragonEgg } from './Consumables/DragonEgg';
import { Ectoplasm } from './Consumables/Ectoplasm';
import { Equinum } from './Consumables/Equinum';
import { FerretFruit } from './Consumables/FerretFruit';
import { FishFillet } from './Consumables/FishFillet';
import { FoxBerry } from './Consumables/FoxBerry';
import { FoxJewel } from './Consumables/FoxJewel';
import { GiantChocolateCupcake } from './Consumables/GiantChocolateCupcake';
import { GoblinAle } from './Consumables/GoblinAle';
import { GodsMead } from './Consumables/GodsMead';
import { GoldenSeed } from './Consumables/GoldenSeed';
import { GroPlus } from './Consumables/GroPlus';
import { HairExtensionSerum } from './Consumables/HairExtensionSerum';
import { HerbalContraceptive } from './Consumables/HerbalContraceptive';
import { Hummus } from './Consumables/Hummus';
import { ImpFood } from './Consumables/ImpFood';
import { IncubusDraft } from './Consumables/IncubusDraft';
import { IsabellaMilk } from './Consumables/IsabellaMilk';
import { KangaFruit } from './Consumables/KangaFruit';
import { KitsuneGift } from './Consumables/KitsuneGift';
import { LaBova } from './Consumables/LaBova';
import { Lactaid } from './Consumables/Lactaid';
import { LustDraft } from './Consumables/LustDraft';
import { LustStick } from './Consumables/LustStick';
import { MarbleMilk } from './Consumables/MarbleMilk';
import { MinotaurBlood } from './Consumables/MinotaurBlood';
import { MinotaurCum } from './Consumables/MinotaurCum';
import { MouseCocoa } from './Consumables/MouseCocoa';
import { NeonPinkEgg } from './Consumables/NeonPinkEgg';
import { NumbRock } from './Consumables/NumbRock';
import { OvipositionElixir } from './Consumables/OvipositionElixir';
import { PeppermintWhite } from './Consumables/PeppermintWhite';
import { PhoukaWhiskey } from './Consumables/PhoukaWhiskey';
import { PrincessPucker } from './Consumables/PrincessPucker';
import { PurePearl } from './Consumables/PurePearl';
import { PurityPeach } from './Consumables/PurityPeach';
import { PurpleFruit } from './Consumables/PurpleFruit';
import { Reducto } from './Consumables/Reducto';
import { Reptilum } from './Consumables/Reptilum';
import { RingtailFig } from './Consumables/RingtailFig';
import { RizzaRoot } from './Consumables/RizzaRoot';
import { ScholarsTea } from './Consumables/ScholarsTea';
import { SensitivityDraft } from './Consumables/SensitivityDraft';
import { SharkTooth } from './Consumables/SharkTooth';
import { SheepMilk } from './Consumables/SheepMilk';
import { ShriveledTentacle } from './Consumables/ShriveledTentacle';
import { SnakeOil } from './Consumables/SnakeOil';
import { SuccubiMilk } from './Consumables/SuccubiMilk';
import { SuccubisDelight } from './Consumables/SuccubisDelight';
import { SuccubisDream } from './Consumables/SuccubisDream';
import { SweetGossamer } from './Consumables/SweetGossamer';
import { TatteredScroll } from './Consumables/TatteredScroll';
import { TrapOil } from './Consumables/TrapOil';
import { VitalityTincture } from './Consumables/VitalityTincture';
import { WetCloth } from './Consumables/WetCloth';
import { WhiskerFruit } from './Consumables/WhiskerFruit';
import { WhiteSpellbook } from './Consumables/WhiteSpellbook';
import { ItemDict } from 'Engine/Items/ItemDict';

ItemDict.add(new BeeHoney(false, false));
ItemDict.add(new BeeHoney(true, false));
ItemDict.add(new BeeHoney(false, true));
ItemDict.add(new BimboLiqueur());
ItemDict.add(new BlackCatBeer());
ItemDict.add(new BlackSpellbook());
ItemDict.add(new BroBrew());
ItemDict.add(new CaninePepper(CaninePepperType.Normal));
ItemDict.add(new CaninePepper(CaninePepperType.Oversized));
ItemDict.add(new CaninePepper(CaninePepperType.Double));
ItemDict.add(new CaninePepper(CaninePepperType.Black));
ItemDict.add(new CaninePepper(CaninePepperType.Knotty));
ItemDict.add(new CaninePepper(CaninePepperType.Bulbous));
ItemDict.add(new CeruleanPotion());
ItemDict.add(new Coal());
ItemDict.add(new DeBimbo());
ItemDict.add(new DragonEgg());
ItemDict.add(new Ectoplasm());
ItemDict.add(new Eggs(EggType.Black, false));
ItemDict.add(new Eggs(EggType.Blue, false));
ItemDict.add(new Eggs(EggType.Brown, false));
ItemDict.add(new Eggs(EggType.Pink, false));
ItemDict.add(new Eggs(EggType.Purple, false));
ItemDict.add(new Eggs(EggType.White, false));
ItemDict.add(new Eggs(EggType.Black, true));
ItemDict.add(new Eggs(EggType.Blue, true));
ItemDict.add(new Eggs(EggType.Brown, true));
ItemDict.add(new Eggs(EggType.Pink, true));
ItemDict.add(new Eggs(EggType.Purple, true));
ItemDict.add(new Eggs(EggType.White, true));
ItemDict.add(new Equinum());
ItemDict.add(new FerretFruit());
ItemDict.add(new FishFillet());
ItemDict.add(new FoxBerry(false));
ItemDict.add(new FoxBerry(true));
ItemDict.add(new FoxJewel(false));
ItemDict.add(new FoxJewel(true));
ItemDict.add(new GiantChocolateCupcake());
ItemDict.add(new GoblinAle());
ItemDict.add(new GodsMead());
ItemDict.add(new GoldenSeed(false));
ItemDict.add(new GoldenSeed(true));
ItemDict.add(new GroPlus());
ItemDict.add(new HairDye(HairDyeType.Auburn));
ItemDict.add(new HairDye(HairDyeType.Black));
ItemDict.add(new HairDye(HairDyeType.Blonde));
ItemDict.add(new HairDye(HairDyeType.BrightOrange));
ItemDict.add(new HairDye(HairDyeType.Brown));
ItemDict.add(new HairDye(HairDyeType.DarkBlue));
ItemDict.add(new HairDye(HairDyeType.Gray));
ItemDict.add(new HairDye(HairDyeType.Green));
ItemDict.add(new HairDye(HairDyeType.NeonPink));
ItemDict.add(new HairDye(HairDyeType.Purple));
ItemDict.add(new HairDye(HairDyeType.Red));
ItemDict.add(new HairDye(HairDyeType.White));
ItemDict.add(new HairExtensionSerum());
ItemDict.add(new HerbalContraceptive());
ItemDict.add(new Hummus());
ItemDict.add(new ImpFood());
ItemDict.add(new IncubusDraft(false));
ItemDict.add(new IncubusDraft(true));
ItemDict.add(new IsabellaMilk());
ItemDict.add(new KangaFruit(false));
ItemDict.add(new KangaFruit(true));
ItemDict.add(new KitsuneGift());
ItemDict.add(new LaBova(false, false));
ItemDict.add(new LaBova(true, false));
ItemDict.add(new LaBova(false, true));
ItemDict.add(new Lactaid());
ItemDict.add(new LustDraft(false));
ItemDict.add(new LustDraft(true));
ItemDict.add(new LustStick());
ItemDict.add(new MarbleMilk());
ItemDict.add(new MinotaurBlood());
ItemDict.add(new MinotaurCum());
ItemDict.add(new MouseCocoa());
ItemDict.add(new NeonPinkEgg(false));
ItemDict.add(new NeonPinkEgg(true));
ItemDict.add(new NumbRock());
ItemDict.add(new OvipositionElixir());
ItemDict.add(new PeppermintWhite());
ItemDict.add(new PhoukaWhiskey());
ItemDict.add(new PrincessPucker());
ItemDict.add(new PurePearl());
ItemDict.add(new PurityPeach());
ItemDict.add(new PurpleFruit());
ItemDict.add(new Reducto());
ItemDict.add(new Reptilum());
ItemDict.add(new RingtailFig());
ItemDict.add(new RizzaRoot());
ItemDict.add(new ScholarsTea());
ItemDict.add(new SensitivityDraft());
ItemDict.add(new SharkTooth(false));
ItemDict.add(new SharkTooth(true));
ItemDict.add(new SheepMilk());
ItemDict.add(new ShriveledTentacle());
ItemDict.add(new SnakeOil());
ItemDict.add(new SuccubiMilk(false));
ItemDict.add(new SuccubiMilk(true));
ItemDict.add(new SuccubisDelight(false));
ItemDict.add(new SuccubisDelight(true));
ItemDict.add(new SuccubisDream());
ItemDict.add(new SweetGossamer(false));
ItemDict.add(new SweetGossamer(true));
ItemDict.add(new TatteredScroll());
ItemDict.add(new TrapOil());
ItemDict.add(new VitalityTincture());
ItemDict.add(new WetCloth());
ItemDict.add(new WhiskerFruit());
ItemDict.add(new WhiteSpellbook());
        // ItemDict.add(new WingStick());
