export enum WeaponName {
    Fists = "Fists  ",
    BeautifulSword = "B.Sword",
    LargeClaymore = "Claymor",
    DragonShellShield = "DrgnShl",
    EldritchStaff = "E.Staff",
    UrtaHalberd = "UrtaHlb",
    HookedGauntlet = "H.Gaunt",
    JeweledRapier = "JRapier",
    Katana = "Katana ",
    LargeAxe = "L. Axe ",
    AphroDagger = "L.Daggr",
    LargeHammer = "L.Hammr",
    Pipe = "Pipe   ",
    RidingCrop = "RidingC",
    RaphaelsRapier = "RRapier",
    Spellblade = "S.Blade",
    SpikedGauntlet = "S.Gaunt",
    Spear = "Spear  ",
    SuccubiWhip = "SucWhip",
    WizardsStaff = "W.Staff",
    HugeWarhammer = "Warhamr",
    Whip = "Whip   ",
}
