export const Sprites = {
    1: "urta",
    2: "akbal",
    3: "amily",
    4: "anemone",
    // 5: "None",
    6: "bee girl",
    7: "ceraph",
    8: "cerulean succubus",
    9: "christmas elf",
    10: "dominika cloaked",
    11: "gnoll",
    12: "cotton",
    13: "easter bunny",
    14: "edryn",
    15: "exgartuan",
    16: "factory omnibus",
    17: "faerie",
    18: "fenimp",
    19: "fetish cultist",
    20: "fetish zealot",
    // 21: "None",
    // 22: "None",
    23: "giacomo",
    24: "goblin",
    25: "green slime",
    26: "harpy",
    27: "hellhound",
    28: "ifris",
    29: "imp",
    30: "incubus mechanic",
    31: "isabella",
    32: "izma",
    33: "jasun",
    34: "jojo",
    35: "kelt",
    36: "lottie",
    37: "lumi",
    38: "lynette",
    39: "maddie",
    40: "marae",
    41: "marble",
    42: "marcus and lucia",
    // 43: "None",
    44: "minotaur",
    45: "naga",
    46: "oasis demons",
    47: "oswald",
    // 48: "None",
    49: "rathazul",
    50: "sandwich",
    51: "scylla",
    52: "sean",
    53: "sophie",
    54: "spear gnoll",
    55: "succubus secretary",
    56: "tamani",
    57: "tamani daughters",
    58: "dominika uncloaked",
    59: "vagrant cats",
    60: "vala",
    61: "victoria",
    62: "whitney",
    63: "yara",
    64: "yvonne",
    65: "amily defurr",
    66: "shouldra",
    67: "shouldra ghost",
    68: "hel",
    69: "goo girl",
    70: "sharkgirl",
    71: "kida",
    72: "kiha",
    73: "spidergirl",
    74: "spiderguy",
    75: "basilisk",
    76: "dickworms",
    77: "drider",
    78: "roxanne",
    79: "valeria",
    80: "weaponsmith",
    81: "jojo tentacle",
    82: "scylla and bear",
    83: "sophie bimbo",
    84: "urta drunk",
    85: "vala slave",
    86: "rogar",
    87: "ceraph clothed",
    88: "ceraph goblin",
    89: "chameleon",
    90: "chicken harpy",
    91: "cinnabar",
    92: "corrupted glade",
    93: "lilium",
    94: "minotaur sons",
    95: "minerva",
    96: "mrs coffee",
    97: "sandtrap",
    98: "satyr",
    99: "stuck satyr",
    100: "tentacle monster",
    101: "rubi hornless",
    102: "rubi horns",
    103: "venus",
    104: "kitsune black",
    105: "kitsune blonde",
    106: "kitsune red"

};
