import { kFLAGS } from "./GlobalFlags/kFLAGS";

export type Flags = FlagTypeOverrides &
    Record<Exclude<kFLAGS, keyof FlagTypeOverrides>, number> &
    Record<number, any>;

type FlagTypeOverrides = {
    [kFLAGS.LOW_STANDARDS_FOR_ALL]: boolean;
    [kFLAGS.HYPER_HAPPY]: boolean;
    [kFLAGS.SHOW_SPRITES_FLAG]: boolean;
    [kFLAGS.SILLY_MODE_ENABLE_FLAG]: boolean;
    [kFLAGS.BONUS_ITEM_AFTER_COMBAT_ID]: string;
    [kFLAGS.BENOIT_1]: string;
    [kFLAGS.BENOIT_2]: string;
    [kFLAGS.BENOIT_3]: string;
    [kFLAGS.RIDDLE_ONE]: (() => void) | undefined;
    [kFLAGS.RIDDLE_TWO]: (() => void) | undefined;
    [kFLAGS.RIDDLE_THREE]: (() => void) | undefined;
    [kFLAGS.HELSPAWN_NAME]: string;
    [kFLAGS.HELSPAWN_WEAPON]: "bow" | "scimitar" | "scimitar and shield" | "";
    [kFLAGS.GAR_NAME]: string;
    [kFLAGS.MILK_NAME]: string;
    [kFLAGS.GOO_NAME]: string;
    [kFLAGS.GOO_EYES]: string;
    [kFLAGS.KELLY_HAIR_COLOR]: string;
    [kFLAGS.TEMP_STORAGE_PASTRY_NAME]: string;
    [kFLAGS.PLAYER_DISARMED_WEAPON_ID]: string;
    [kFLAGS.KATHERINE_HAIR_COLOR]: string;
    [kFLAGS.ANEMONE_WEAPON_ID]: string;
    [kFLAGS.SLEEP_WITH]: string;
    [kFLAGS.FOLLOWER_PRODUCTION_SOPHIE_COLORCHOICE]: string;
    [kFLAGS.SOCK_HOLDING]: string;
    [kFLAGS.AMILY_CLOTHING]: string;
    [kFLAGS.ARIAN_EGG_COLOR]: string;
    [kFLAGS.NIEVE_MOUTH]: string;
    [kFLAGS.LETHICE_NAME]: string;
    [kFLAGS.WHITNEY_TATTOO_COLLARBONE]: string;
    [kFLAGS.WHITNEY_TATTOO_SHOULDERS]: string;
    [kFLAGS.WHITNEY_TATTOO_LOWERBACK]: string;
    [kFLAGS.WHITNEY_TATTOO_BUTT]: string;
    [kFLAGS.AMILY_TATTOO_COLLARBONE]: string;
    [kFLAGS.AMILY_TATTOO_LOWERBACK]: string;
    [kFLAGS.AMILY_TATTOO_SHOULDERS]: string;
    [kFLAGS.AMILY_TATTOO_BUTT]: string;
    [kFLAGS.JOJO_TATTOO_COLLARBONE]: string;
    [kFLAGS.JOJO_TATTOO_LOWERBACK]: string;
    [kFLAGS.JOJO_TATTOO_SHOULDERS]: string;
    [kFLAGS.JOJO_TATTOO_BUTT]: string;
    [kFLAGS.SOPHIE_TATTOO_COLLARBONE]: string;
    [kFLAGS.SOPHIE_TATTOO_LOWERBACK]: string;
    [kFLAGS.SOPHIE_TATTOO_SHOULDERS]: string;
    [kFLAGS.SOPHIE_TATTOO_BUTT]: string;
    [kFLAGS.VAPULA_TATTOO_COLLARBONE]: string;
    [kFLAGS.VAPULA_TATTOO_LOWERBACK]: string;
    [kFLAGS.VAPULA_TATTOO_SHOULDERS]: string;
    [kFLAGS.VAPULA_TATTOO_BUTT]: string;
    [kFLAGS.KELLY_TATTOO_COLLARBONE]: string;
    [kFLAGS.KELLY_TATTOO_LOWERBACK]: string;
    [kFLAGS.KELLY_TATTOO_SHOULDERS]: string;
    [kFLAGS.KELLY_TATTOO_BUTT]: string;
    [kFLAGS.MILKY_TATTOO_COLLARBONE]: string;
    [kFLAGS.MILKY_TATTOO_LOWERBACK]: string;
    [kFLAGS.MILKY_TATTOO_SHOULDERS]: string;
    [kFLAGS.MILKY_TATTOO_BUTT]: string;
};

export function createFlags() {
    const flags = {} as Record<number, string | boolean | number>;
    for (let index = 0; index < 3000; index++) flags[index] = 0;
    flags[kFLAGS.LOW_STANDARDS_FOR_ALL] = false;
    flags[kFLAGS.HYPER_HAPPY] = false;
    flags[kFLAGS.SHOW_SPRITES_FLAG] = false;
    flags[kFLAGS.SILLY_MODE_ENABLE_FLAG] = false;
    flags[kFLAGS.BONUS_ITEM_AFTER_COMBAT_ID] = "";
    flags[kFLAGS.BENOIT_1] = "";
    flags[kFLAGS.BENOIT_2] = "";
    flags[kFLAGS.BENOIT_3] = "";
    flags[kFLAGS.HELSPAWN_NAME] = "";
    flags[kFLAGS.HELSPAWN_WEAPON] = "";
    flags[kFLAGS.GAR_NAME] = "";
    flags[kFLAGS.MILK_NAME] = "";
    flags[kFLAGS.GOO_NAME] = "";
    flags[kFLAGS.GOO_EYES] = "";
    flags[kFLAGS.KELLY_HAIR_COLOR] = "";
    flags[kFLAGS.TEMP_STORAGE_PASTRY_NAME] = "";
    flags[kFLAGS.PLAYER_DISARMED_WEAPON_ID] = "";
    flags[kFLAGS.KATHERINE_HAIR_COLOR] = "";
    flags[kFLAGS.ANEMONE_WEAPON_ID] = "";
    flags[kFLAGS.SLEEP_WITH] = "";
    flags[kFLAGS.FOLLOWER_PRODUCTION_SOPHIE_COLORCHOICE] = "";
    flags[kFLAGS.SOCK_HOLDING] = "";
    flags[kFLAGS.AMILY_CLOTHING] = "";
    flags[kFLAGS.ARIAN_EGG_COLOR] = "";
    flags[kFLAGS.NIEVE_MOUTH] = "";
    flags[kFLAGS.LETHICE_NAME] = "";
    flags[kFLAGS.WHITNEY_TATTOO_COLLARBONE] = "";
    flags[kFLAGS.WHITNEY_TATTOO_SHOULDERS] = "";
    flags[kFLAGS.WHITNEY_TATTOO_LOWERBACK] = "";
    flags[kFLAGS.WHITNEY_TATTOO_BUTT] = "";
    flags[kFLAGS.AMILY_TATTOO_COLLARBONE] = "";
    flags[kFLAGS.AMILY_TATTOO_LOWERBACK] = "";
    flags[kFLAGS.AMILY_TATTOO_SHOULDERS] = "";
    flags[kFLAGS.AMILY_TATTOO_BUTT] = "";
    flags[kFLAGS.JOJO_TATTOO_COLLARBONE] = "";
    flags[kFLAGS.JOJO_TATTOO_LOWERBACK] = "";
    flags[kFLAGS.JOJO_TATTOO_SHOULDERS] = "";
    flags[kFLAGS.JOJO_TATTOO_BUTT] = "";
    flags[kFLAGS.SOPHIE_TATTOO_COLLARBONE] = "";
    flags[kFLAGS.SOPHIE_TATTOO_LOWERBACK] = "";
    flags[kFLAGS.SOPHIE_TATTOO_SHOULDERS] = "";
    flags[kFLAGS.SOPHIE_TATTOO_BUTT] = "";
    flags[kFLAGS.VAPULA_TATTOO_COLLARBONE] = "";
    flags[kFLAGS.VAPULA_TATTOO_LOWERBACK] = "";
    flags[kFLAGS.VAPULA_TATTOO_SHOULDERS] = "";
    flags[kFLAGS.VAPULA_TATTOO_BUTT] = "";
    flags[kFLAGS.KELLY_TATTOO_COLLARBONE] = "";
    flags[kFLAGS.KELLY_TATTOO_LOWERBACK] = "";
    flags[kFLAGS.KELLY_TATTOO_SHOULDERS] = "";
    flags[kFLAGS.KELLY_TATTOO_BUTT] = "";
    flags[kFLAGS.MILKY_TATTOO_COLLARBONE] = "";
    flags[kFLAGS.MILKY_TATTOO_LOWERBACK] = "";
    flags[kFLAGS.MILKY_TATTOO_SHOULDERS] = "";
    flags[kFLAGS.MILKY_TATTOO_BUTT] = "";

    return flags as Flags;
}
