export enum TokenType {
    Identity = 'identity',
    Escape = 'escape',
    BracketOpen = 'bracket open',
    BracketClose = 'bracket close',
    ParenthesisOpen = 'parenthesis open',
    ParenthesisClose = 'parenthesis close',
    Equal = 'equal',
    SingleEqual = 'single equal',
    NotEqual = 'not equal',
    LessThan = 'less than',
    LessThanOrEqual = 'less than or equal',
    GreaterThan = 'greater than',
    GreaterThanOrEqual = 'greater than or equal',
    Whitespace = 'whitespace',
    If = 'if',
    Bar = 'bar',
    Number = 'number',
    String = 'string',
    Ignore = 'ignore',
    Error = 'error',
}
