import { StatusEffectType } from './StatusEffectType';
import { Dictionary } from '../../Engine/Utilities/Dictionary';
import { EffectDesc } from './EffectDescription';

export const StatusEffectDescLib = new Dictionary<StatusEffectType, EffectDesc>();
StatusEffectDescLib.set(StatusEffectType.AllNaturalOnaholeUsed, new EffectDesc(StatusEffectType.AllNaturalOnaholeUsed, "AllNaturalOnaholeUsed", "all-natural onahole used", ""));
StatusEffectDescLib.set(StatusEffectType.AteEgg, new EffectDesc(StatusEffectType.AteEgg, "AteEgg", "ateEgg", ""));
StatusEffectDescLib.set(StatusEffectType.AnemoneArousal, new EffectDesc(StatusEffectType.AnemoneArousal, "AnemoneArousal", "Anemone Arousal", ""));
StatusEffectDescLib.set(StatusEffectType.BimboChampagne, new EffectDesc(StatusEffectType.BimboChampagne, "BimboChampagne", "Bimbo Champagne", ""));
StatusEffectDescLib.set(StatusEffectType.Birthed, new EffectDesc(StatusEffectType.Birthed, "Birthed", "Birthed", ""));
StatusEffectDescLib.set(StatusEffectType.BirthedImps, new EffectDesc(StatusEffectType.BirthedImps, "BirthedImps", "Birthed Imps", ""));
StatusEffectDescLib.set(StatusEffectType.BlackCatBeer, new EffectDesc(StatusEffectType.BlackCatBeer, "BlackCatBeer", "Black Cat Beer", ""));
StatusEffectDescLib.set(StatusEffectType.BlackNipples, new EffectDesc(StatusEffectType.BlackNipples, "BlackNipples", "Black Nipples", ""));
StatusEffectDescLib.set(StatusEffectType.BlowjobOn, new EffectDesc(StatusEffectType.BlowjobOn, "BlowjobOn", "BlowjobOn", ""));
StatusEffectDescLib.set(StatusEffectType.BoatDiscovery, new EffectDesc(StatusEffectType.BoatDiscovery, "BoatDiscovery", "Boat Discovery", ""));
StatusEffectDescLib.set(StatusEffectType.BonusACapacity, new EffectDesc(StatusEffectType.BonusACapacity, "BonusACapacity", "Bonus aCapacity", ""));
StatusEffectDescLib.set(StatusEffectType.BonusVCapacity, new EffectDesc(StatusEffectType.BonusVCapacity, "BonusVCapacity", "Bonus vCapacity", ""));
StatusEffectDescLib.set(StatusEffectType.BottledMilk, new EffectDesc(StatusEffectType.BottledMilk, "BottledMilk", "Bottled Milk", ""));
StatusEffectDescLib.set(StatusEffectType.BreastsMilked, new EffectDesc(StatusEffectType.BreastsMilked, "BreastsMilked", "Breasts Milked", ""));
StatusEffectDescLib.set(StatusEffectType.BSwordBroken, new EffectDesc(StatusEffectType.BSwordBroken, "BSwordBroken", "BSwordBroken", ""));
StatusEffectDescLib.set(StatusEffectType.BuiltMilker, new EffectDesc(StatusEffectType.BuiltMilker, "BuiltMilker", "BUILT: Milker", ""));
StatusEffectDescLib.set(StatusEffectType.BurpChanged, new EffectDesc(StatusEffectType.BurpChanged, "BurpChanged", "Burp Changed", ""));
StatusEffectDescLib.set(StatusEffectType.ButtStretched, new EffectDesc(StatusEffectType.ButtStretched, "ButtStretched", "ButtStretched", ""));
StatusEffectDescLib.set(StatusEffectType.CampAnemoneTrigger, new EffectDesc(StatusEffectType.CampAnemoneTrigger, "CampAnemoneTrigger", "Camp Anemone Trigger", ""));
StatusEffectDescLib.set(StatusEffectType.CampMarble, new EffectDesc(StatusEffectType.CampMarble, "CampMarble", "Camp Marble", ""));
StatusEffectDescLib.set(StatusEffectType.CampRathazul, new EffectDesc(StatusEffectType.CampRathazul, "CampRathazul", "Camp Rathazul", ""));
StatusEffectDescLib.set(StatusEffectType.ClaraCombatRounds, new EffectDesc(StatusEffectType.ClaraCombatRounds, "ClaraCombatRounds", "Clara Combat Rounds", ""));
StatusEffectDescLib.set(StatusEffectType.ClaraFoughtInCamp, new EffectDesc(StatusEffectType.ClaraFoughtInCamp, "ClaraFoughtInCamp", "Clara Fought In Camp", ""));
StatusEffectDescLib.set(StatusEffectType.CockPumped, new EffectDesc(StatusEffectType.CockPumped, "CockPumped", "Cock Pumped", ""));
StatusEffectDescLib.set(StatusEffectType.Contraceptives, new EffectDesc(StatusEffectType.Contraceptives, "Contraceptives", "Contraceptives", ""));
StatusEffectDescLib.set(StatusEffectType.CuntStretched, new EffectDesc(StatusEffectType.CuntStretched, "CuntStretched", "CuntStretched", ""));
StatusEffectDescLib.set(StatusEffectType.DefenseCanopy, new EffectDesc(StatusEffectType.DefenseCanopy, "DefenseCanopy", "Defense: Canopy", ""));
StatusEffectDescLib.set(StatusEffectType.DeluxeOnaholeUsed, new EffectDesc(StatusEffectType.DeluxeOnaholeUsed, "DeluxeOnaholeUsed", "deluxe onahole used", ""));
StatusEffectDescLib.set(StatusEffectType.DogWarning, new EffectDesc(StatusEffectType.DogWarning, "DogWarning", "dog warning", ""));
StatusEffectDescLib.set(StatusEffectType.DragonBreathBoost, new EffectDesc(StatusEffectType.DragonBreathBoost, "DragonBreathBoost", "Dragon Breath Boost", ""));
StatusEffectDescLib.set(StatusEffectType.DragonBreathCooldown, new EffectDesc(StatusEffectType.DragonBreathCooldown, "DragonBreathCooldown", "Dragon Breath Cooldown", ""));
StatusEffectDescLib.set(StatusEffectType.DungeonShutDown, new EffectDesc(StatusEffectType.DungeonShutDown, "DungeonShutDown", "DungeonShutDown", ""));
StatusEffectDescLib.set(StatusEffectType.Dysfunction, new EffectDesc(StatusEffectType.Dysfunction, "Dysfunction", "dysfunction", ""));
StatusEffectDescLib.set(StatusEffectType.Edryn, new EffectDesc(StatusEffectType.Edryn, "Edryn", "Edryn", ""));
StatusEffectDescLib.set(StatusEffectType.Eggchest, new EffectDesc(StatusEffectType.Eggchest, "Eggchest", "eggchest", ""));
StatusEffectDescLib.set(StatusEffectType.Eggs, new EffectDesc(StatusEffectType.Eggs, "Eggs", "eggs", ""));
StatusEffectDescLib.set(StatusEffectType.EmberFuckCooldown, new EffectDesc(StatusEffectType.EmberFuckCooldown, "EmberFuckCooldown", "ember fuck cooldown", ""));
StatusEffectDescLib.set(StatusEffectType.EmberNapping, new EffectDesc(StatusEffectType.EmberNapping, "EmberNapping", "Ember Napping", ""));
StatusEffectDescLib.set(StatusEffectType.EverRapedJojo, new EffectDesc(StatusEffectType.EverRapedJojo, "EverRapedJojo", "Ever Raped Jojo", ""));
StatusEffectDescLib.set(StatusEffectType.Exgartuan, new EffectDesc(StatusEffectType.Exgartuan, "Exgartuan", "Exgartuan", ""));
StatusEffectDescLib.set(StatusEffectType.ExploredDeepwoods, new EffectDesc(StatusEffectType.ExploredDeepwoods, "ExploredDeepwoods", "exploredDeepwoods", ""));
StatusEffectDescLib.set(StatusEffectType.FactoryOmnibusDefeated, new EffectDesc(StatusEffectType.FactoryOmnibusDefeated, "FactoryOmnibusDefeated", "FactoryOmnibusDefeated", ""));
StatusEffectDescLib.set(StatusEffectType.FactoryOverload, new EffectDesc(StatusEffectType.FactoryOverload, "FactoryOverload", "FactoryOverload", ""));
StatusEffectDescLib.set(StatusEffectType.FactoryIncubusDefeated, new EffectDesc(StatusEffectType.FactoryIncubusDefeated, "FactoryIncubusDefeated", "FactoryIncubusDefeated", ""));
StatusEffectDescLib.set(StatusEffectType.FactorySuccubusDefeated, new EffectDesc(StatusEffectType.FactorySuccubusDefeated, "FactorySuccubusDefeated", "FactorySuccubusDefeated", ""));
StatusEffectDescLib.set(StatusEffectType.FaerieFemFuck, new EffectDesc(StatusEffectType.FaerieFemFuck, "FaerieFemFuck", "Faerie Fem Fuck", ""));
StatusEffectDescLib.set(StatusEffectType.FaerieFucked, new EffectDesc(StatusEffectType.FaerieFucked, "FaerieFucked", "Faerie Fucked", ""));
StatusEffectDescLib.set(StatusEffectType.FappedGenderless, new EffectDesc(StatusEffectType.FappedGenderless, "FappedGenderless", "fapped genderless", ""));
StatusEffectDescLib.set(StatusEffectType.Feeder, new EffectDesc(StatusEffectType.Feeder, "Feeder", "Feeder", ""));
StatusEffectDescLib.set(StatusEffectType.Fertilized, new EffectDesc(StatusEffectType.Fertilized, "Fertilized", "Fertilized", ""));
StatusEffectDescLib.set(StatusEffectType.FetishOn, new EffectDesc(StatusEffectType.FetishOn, "FetishOn", "fetishON", ""));
StatusEffectDescLib.set(StatusEffectType.FoundFactory, new EffectDesc(StatusEffectType.FoundFactory, "FoundFactory", "Found Factory", ""));
StatusEffectDescLib.set(StatusEffectType.FuckedMarble, new EffectDesc(StatusEffectType.FuckedMarble, "FuckedMarble", "FuckedMarble", ""));
StatusEffectDescLib.set(StatusEffectType.Goojob, new EffectDesc(StatusEffectType.Goojob, "Goojob", "GOOJOB", ""));
StatusEffectDescLib.set(StatusEffectType.GooStuffed, new EffectDesc(StatusEffectType.GooStuffed, "GooStuffed", "gooStuffed", ""));
StatusEffectDescLib.set(StatusEffectType.Groundpound, new EffectDesc(StatusEffectType.Groundpound, "Groundpound", "Groundpound", ""));
StatusEffectDescLib.set(StatusEffectType.HairdresserMeeting, new EffectDesc(StatusEffectType.HairdresserMeeting, "HairdresserMeeting", "hairdresser meeting", ""));
StatusEffectDescLib.set(StatusEffectType.Hangover, new EffectDesc(StatusEffectType.Hangover, "Hangover", "Hangover", ""));
StatusEffectDescLib.set(StatusEffectType.Heat, new EffectDesc(StatusEffectType.Heat, "Heat", "heat", ""));
StatusEffectDescLib.set(StatusEffectType.HorseWarning, new EffectDesc(StatusEffectType.HorseWarning, "HorseWarning", "horse warning", ""));
StatusEffectDescLib.set(StatusEffectType.ImmolationSpell, new EffectDesc(StatusEffectType.ImmolationSpell, "ImmolationSpell", "Immolation Spell", ""));
StatusEffectDescLib.set(StatusEffectType.ImpGangBang, new EffectDesc(StatusEffectType.ImpGangBang, "ImpGangBang", "Imp GangBang", ""));
StatusEffectDescLib.set(StatusEffectType.IncubusBribed, new EffectDesc(StatusEffectType.IncubusBribed, "IncubusBribed", "IncubusBribed", ""));
StatusEffectDescLib.set(StatusEffectType.Infested, new EffectDesc(StatusEffectType.Infested, "Infested", "infested", ""));
StatusEffectDescLib.set(StatusEffectType.IzmaBlowing, new EffectDesc(StatusEffectType.IzmaBlowing, "IzmaBlowing", "IzmaBlowing", ""));
StatusEffectDescLib.set(StatusEffectType.IzumisPipeSmoke, new EffectDesc(StatusEffectType.IzumisPipeSmoke, "IzumisPipeSmoke", "Izumis Pipe Smoke", ""));
StatusEffectDescLib.set(StatusEffectType.JerkingIzma, new EffectDesc(StatusEffectType.JerkingIzma, "JerkingIzma", "JerkingIzma", ""));
StatusEffectDescLib.set(StatusEffectType.Jizzpants, new EffectDesc(StatusEffectType.Jizzpants, "Jizzpants", "Jizzpants", ""));
StatusEffectDescLib.set(StatusEffectType.JojoMeditationCount, new EffectDesc(StatusEffectType.JojoMeditationCount, "JojoMeditationCount", "Jojo Meditation Count", ""));
StatusEffectDescLib.set(StatusEffectType.JojoNightWatch, new EffectDesc(StatusEffectType.JojoNightWatch, "JojoNightWatch", "JojoNightWatch", ""));
StatusEffectDescLib.set(StatusEffectType.JojoTFOffer, new EffectDesc(StatusEffectType.JojoTFOffer, "JojoTFOffer", "JojoTFOffer", ""));
StatusEffectDescLib.set(StatusEffectType.Kelt, new EffectDesc(StatusEffectType.Kelt, "Kelt", "Kelt", ""));
StatusEffectDescLib.set(StatusEffectType.KeltBJ, new EffectDesc(StatusEffectType.KeltBJ, "KeltBJ", "KeltBJ", ""));
StatusEffectDescLib.set(StatusEffectType.KeltBadEndWarning, new EffectDesc(StatusEffectType.KeltBadEndWarning, "KeltBadEndWarning", "Kelt Bad End Warning", ""));
StatusEffectDescLib.set(StatusEffectType.KeltOff, new EffectDesc(StatusEffectType.KeltOff, "KeltOff", "KeltOff", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsArouse, new EffectDesc(StatusEffectType.KnowsArouse, "KnowsArouse", "Knows Arouse", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsBlind, new EffectDesc(StatusEffectType.KnowsBlind, "KnowsBlind", "Knows Blind", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsCharge, new EffectDesc(StatusEffectType.KnowsCharge, "KnowsCharge", "Knows Charge", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsHeal, new EffectDesc(StatusEffectType.KnowsHeal, "KnowsHeal", "Knows Heal", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsMight, new EffectDesc(StatusEffectType.KnowsMight, "KnowsMight", "Knows Might", ""));
StatusEffectDescLib.set(StatusEffectType.KnowsWhitefire, new EffectDesc(StatusEffectType.KnowsWhitefire, "KnowsWhitefire", "Knows Whitefire", ""));
StatusEffectDescLib.set(StatusEffectType.LactationEndurance, new EffectDesc(StatusEffectType.LactationEndurance, "LactationEndurance", "Lactation Endurance", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduction, new EffectDesc(StatusEffectType.LactationReduction, "LactationReduction", "Lactation Reduction", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc0, new EffectDesc(StatusEffectType.LactationReduc0, "LactationReduc0", "Lactation Reduc0", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc1, new EffectDesc(StatusEffectType.LactationReduc1, "LactationReduc1", "Lactation Reduc1", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc2, new EffectDesc(StatusEffectType.LactationReduc2, "LactationReduc2", "Lactation Reduc2", ""));
StatusEffectDescLib.set(StatusEffectType.LactationReduc3, new EffectDesc(StatusEffectType.LactationReduc3, "LactationReduc3", "Lactation Reduc3", ""));
StatusEffectDescLib.set(StatusEffectType.LootEgg, new EffectDesc(StatusEffectType.LootEgg, "LootEgg", "lootEgg", ""));
StatusEffectDescLib.set(StatusEffectType.LostVillagerSpecial, new EffectDesc(StatusEffectType.LostVillagerSpecial, "LostVillagerSpecial", "lostVillagerSpecial", ""));
StatusEffectDescLib.set(StatusEffectType.LustStick, new EffectDesc(StatusEffectType.LustStick, "Luststick", "Luststick", ""));
StatusEffectDescLib.set(StatusEffectType.LustStickApplied, new EffectDesc(StatusEffectType.LustStickApplied, "LustStickApplied", "Lust Stick Applied", ""));
StatusEffectDescLib.set(StatusEffectType.LustyTongue, new EffectDesc(StatusEffectType.LustyTongue, "LustyTongue", "LustyTongue", ""));
StatusEffectDescLib.set(StatusEffectType.MalonVisitedPostAddiction, new EffectDesc(StatusEffectType.MalonVisitedPostAddiction, "MalonVisitedPostAddiction", "Malon Visited Post Addiction", ""));
StatusEffectDescLib.set(StatusEffectType.MaraeComplete, new EffectDesc(StatusEffectType.MaraeComplete, "MaraeComplete", "Marae Complete", ""));
StatusEffectDescLib.set(StatusEffectType.MaraesLethicite, new EffectDesc(StatusEffectType.MaraesLethicite, "MaraesLethicite", "Marae's Lethicite", ""));
StatusEffectDescLib.set(StatusEffectType.MaraesQuestStart, new EffectDesc(StatusEffectType.MaraesQuestStart, "MaraesQuestStart", "Marae's Quest Start", ""));
StatusEffectDescLib.set(StatusEffectType.Marble, new EffectDesc(StatusEffectType.Marble, "Marble", "Marble", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleHasItem, new EffectDesc(StatusEffectType.MarbleHasItem, "MarbleHasItem", "MarbleHasItem", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleItemCooldown, new EffectDesc(StatusEffectType.MarbleItemCooldown, "MarbleItemCooldown", "MarbleItemCooldown", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleRapeAttempted, new EffectDesc(StatusEffectType.MarbleRapeAttempted, "MarbleRapeAttempted", "Marble Rape Attempted", ""));
StatusEffectDescLib.set(StatusEffectType.MarblesMilk, new EffectDesc(StatusEffectType.MarblesMilk, "MarblesMilk", "Marbles Milk", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleSpecials, new EffectDesc(StatusEffectType.MarbleSpecials, "MarbleSpecials", "MarbleSpecials", ""));
StatusEffectDescLib.set(StatusEffectType.MarbleWithdrawl, new EffectDesc(StatusEffectType.MarbleWithdrawl, "MarbleWithdrawl", "MarbleWithdrawl", ""));
StatusEffectDescLib.set(StatusEffectType.Meditated, new EffectDesc(StatusEffectType.Meditated, "Meditated", "Meditated", ""));
StatusEffectDescLib.set(StatusEffectType.MeanToNaga, new EffectDesc(StatusEffectType.MeanToNaga, "MeanToNaga", "MeanToNaga", ""));
StatusEffectDescLib.set(StatusEffectType.MeetWanderer, new EffectDesc(StatusEffectType.MeetWanderer, "MeetWanderer", "meet wanderer", ""));
StatusEffectDescLib.set(StatusEffectType.MetCorruptMarae, new EffectDesc(StatusEffectType.MetCorruptMarae, "MetCorruptMarae", "Met Corrupt Marae", ""));
StatusEffectDescLib.set(StatusEffectType.MetMarae, new EffectDesc(StatusEffectType.MetMarae, "MetMarae", "Met Marae", ""));
StatusEffectDescLib.set(StatusEffectType.MetRathazul, new EffectDesc(StatusEffectType.MetRathazul, "MetRathazul", "metRathazul", ""));
StatusEffectDescLib.set(StatusEffectType.MetWorms, new EffectDesc(StatusEffectType.MetWorms, "MetWorms", "metWorms", ""));
StatusEffectDescLib.set(StatusEffectType.MetWhitney, new EffectDesc(StatusEffectType.MetWhitney, "MetWhitney", "Met Whitney", ""));
StatusEffectDescLib.set(StatusEffectType.Milked, new EffectDesc(StatusEffectType.Milked, "Milked", "Milked", ""));
StatusEffectDescLib.set(StatusEffectType.MinoPlusCowgirl, new EffectDesc(StatusEffectType.MinoPlusCowgirl, "MinoPlusCowgirl", "Mino + Cowgirl", ""));
StatusEffectDescLib.set(StatusEffectType.Naga, new EffectDesc(StatusEffectType.Naga, "Naga", "Naga", ""));
StatusEffectDescLib.set(StatusEffectType.NakedOn, new EffectDesc(StatusEffectType.NakedOn, "NakedOn", "NakedOn", ""));
StatusEffectDescLib.set(StatusEffectType.NoJojo, new EffectDesc(StatusEffectType.NoJojo, "NoJojo", "noJojo", ""));
StatusEffectDescLib.set(StatusEffectType.NoMoreMarble, new EffectDesc(StatusEffectType.NoMoreMarble, "NoMoreMarble", "No More Marble", ""));
StatusEffectDescLib.set(StatusEffectType.Oswald, new EffectDesc(StatusEffectType.Oswald, "Oswald", "Oswald", ""));
StatusEffectDescLib.set(StatusEffectType.PlainOnaholeUsed, new EffectDesc(StatusEffectType.PlainOnaholeUsed, "PlainOnaholeUsed", "plain onahole used", ""));
StatusEffectDescLib.set(StatusEffectType.PhoukaWhiskeyAffect, new EffectDesc(StatusEffectType.PhoukaWhiskeyAffect, "PhoukaWhiskeyAffect", "PhoukaWhiskeyAffect", ""));
StatusEffectDescLib.set(StatusEffectType.PostAkbalSubmission, new EffectDesc(StatusEffectType.PostAkbalSubmission, "PostAkbalSubmission", "Post Akbal Submission", ""));
StatusEffectDescLib.set(StatusEffectType.PostAnemoneBeatdown, new EffectDesc(StatusEffectType.PostAnemoneBeatdown, "PostAnemoneBeatdown", "Post Anemone Beatdown", ""));
StatusEffectDescLib.set(StatusEffectType.PureCampJojo, new EffectDesc(StatusEffectType.PureCampJojo, "PureCampJojo", "PureCampJojo", ""));
StatusEffectDescLib.set(StatusEffectType.RathazulArmor, new EffectDesc(StatusEffectType.RathazulArmor, "RathazulArmor", "RathazulArmor", ""));
StatusEffectDescLib.set(StatusEffectType.RepeatSuccubi, new EffectDesc(StatusEffectType.RepeatSuccubi, "RepeatSuccubi", "repeatSuccubi", ""));
StatusEffectDescLib.set(StatusEffectType.Rut, new EffectDesc(StatusEffectType.Rut, "Rut", "rut", ""));
StatusEffectDescLib.set(StatusEffectType.SharkGirl, new EffectDesc(StatusEffectType.SharkGirl, "SharkGirl", "Shark-Girl", ""));
StatusEffectDescLib.set(StatusEffectType.ShieldingSpell, new EffectDesc(StatusEffectType.ShieldingSpell, "ShieldingSpell", "Shielding Spell", ""));
StatusEffectDescLib.set(StatusEffectType.SlimeCraving, new EffectDesc(StatusEffectType.SlimeCraving, "SlimeCraving", "Slime Craving", ""));
StatusEffectDescLib.set(StatusEffectType.SlimeCravingFeed, new EffectDesc(StatusEffectType.SlimeCravingFeed, "SlimeCravingFeed", "Slime Craving Feed", ""));
StatusEffectDescLib.set(StatusEffectType.SlimeCravingOutput, new EffectDesc(StatusEffectType.SlimeCravingOutput, "SlimeCravingOutput", "Slime Craving Output", ""));
StatusEffectDescLib.set(StatusEffectType.SuccubiFirst, new EffectDesc(StatusEffectType.SuccubiFirst, "SuccubiFirst", "SuccubiFirst", ""));
StatusEffectDescLib.set(StatusEffectType.SuccubiNight, new EffectDesc(StatusEffectType.SuccubiNight, "SuccubiNight", "succubiNight", ""));
StatusEffectDescLib.set(StatusEffectType.TakenGroPlus, new EffectDesc(StatusEffectType.TakenGroPlus, "TakenGroPlus", "TakenGro+", ""));
StatusEffectDescLib.set(StatusEffectType.TakenLactaid, new EffectDesc(StatusEffectType.TakenLactaid, "TakenLactaid", "TakenLactaid", ""));
// Used only for compatibility with old save files, otherwise no longer in use
StatusEffectDescLib.set(StatusEffectType.Tamani, new EffectDesc(StatusEffectType.Tamani, "Tamani", "Tamani", ""));
// Used only for compatibility with old save files, otherwise no longer in use
StatusEffectDescLib.set(StatusEffectType.TamaniFemaleEncounter, new EffectDesc(StatusEffectType.TamaniFemaleEncounter, "TamaniFemaleEncounter", "Tamani Female Encounter", ""));
StatusEffectDescLib.set(StatusEffectType.TelAdre, new EffectDesc(StatusEffectType.TelAdre, "TelAdre", "Tel'Adre", ""));
StatusEffectDescLib.set(StatusEffectType.TentacleBadEndCounter, new EffectDesc(StatusEffectType.TentacleBadEndCounter, "TentacleBadEndCounter", "TentacleBadEndCounter", ""));
StatusEffectDescLib.set(StatusEffectType.TentacleJojo, new EffectDesc(StatusEffectType.TentacleJojo, "TentacleJojo", "Tentacle Jojo", ""));
StatusEffectDescLib.set(StatusEffectType.TensionReleased, new EffectDesc(StatusEffectType.TensionReleased, "TensionReleased", "TensionReleased", ""));
StatusEffectDescLib.set(StatusEffectType.TF2, new EffectDesc(StatusEffectType.TF2, "TF2", "TF2", ""));
StatusEffectDescLib.set(StatusEffectType.TookBlessedSword, new EffectDesc(StatusEffectType.TookBlessedSword, "TookBlessedSword", "Took Blessed Sword", ""));
/**
 * v1 = bonus index
 * v2 = bonus value
 * v3 = remaining time
 */
StatusEffectDescLib.set(StatusEffectType.UmasMassage, new EffectDesc(StatusEffectType.UmasMassage, "UmasMassage", "Uma's Massage", ""));
StatusEffectDescLib.set(StatusEffectType.Uniball, new EffectDesc(StatusEffectType.Uniball, "Uniball", "Uniball", ""));
StatusEffectDescLib.set(StatusEffectType.UsedNaturalSelfStim, new EffectDesc(StatusEffectType.UsedNaturalSelfStim, "UsedNaturalSelfStim", "used natural self-stim", ""));
StatusEffectDescLib.set(StatusEffectType.used_self_dash_stim, new EffectDesc(StatusEffectType.used_self_dash_stim, "used_self_dash_stim", "used self-stim", ""));
StatusEffectDescLib.set(StatusEffectType.Victoria, new EffectDesc(StatusEffectType.Victoria, "Victoria", "Victoria", ""));
StatusEffectDescLib.set(StatusEffectType.VoluntaryDemonpack, new EffectDesc(StatusEffectType.VoluntaryDemonpack, "VoluntaryDemonpack", "Voluntary Demonpack", ""));
StatusEffectDescLib.set(StatusEffectType.WormOffer, new EffectDesc(StatusEffectType.WormOffer, "WormOffer", "WormOffer", ""));
StatusEffectDescLib.set(StatusEffectType.WormPlugged, new EffectDesc(StatusEffectType.WormPlugged, "WormPlugged", "worm plugged", ""));
StatusEffectDescLib.set(StatusEffectType.WormsHalf, new EffectDesc(StatusEffectType.WormsHalf, "WormsHalf", "wormsHalf", ""));
StatusEffectDescLib.set(StatusEffectType.WormsOff, new EffectDesc(StatusEffectType.WormsOff, "WormsOff", "wormsOff", ""));
StatusEffectDescLib.set(StatusEffectType.WormsOn, new EffectDesc(StatusEffectType.WormsOn, "WormsOn", "wormsOn", ""));
StatusEffectDescLib.set(StatusEffectType.WandererDemon, new EffectDesc(StatusEffectType.WandererDemon, "WandererDemon", "wanderer demon", ""));
StatusEffectDescLib.set(StatusEffectType.WandererHuman, new EffectDesc(StatusEffectType.WandererHuman, "WandererHuman", "wanderer human", ""));
StatusEffectDescLib.set(StatusEffectType.Yara, new EffectDesc(StatusEffectType.Yara, "Yara", "Yara", ""));
