export enum PregnancyType {
    IMP = "Imp",
    MINOTAUR = "Minotaur",
    MOUSE = "Mouse",
    OVIELIXIR_EGGS = "Ovielixir Eggs",
    HELL_HOUND = "Hell Hound",
    CENTAUR = "Centaur",
    MARBLE = "Marble",
    BUNNY = "Bunny",
    ANEMONE = "Anemone",
    AMILY = "Amily",
    IZMA = "Izma",
    SPIDER = "Spider",
    BASILISK = "Basilisk",
    DRIDER_EGGS = "Drider Eggs",
    GOO_GIRL = "Goo Girl",
    EMBER = "Ember",
    BENOIT = "Benoit",
    SATYR = "Satyr",
    COTTON = "Cotton",
    URTA = "Urta",
    SAND_WITCH = "Sand Witch",
    FROG_GIRL = "Frog Girl",
    FAERIE = "Faerie",
    PLAYER = "Player",
    BEE_EGGS = "Bee Eggs",
    SANDTRAP_FERTILE = "Sandtrap Fertile",
    SANDTRAP = "Sandtrap",
    JOJO = "Jojo",
    KELT = "Kelt",
    TAOTH = "Taoth",
    GOO_STUFFED = "Goo Stuffed",
    // form of pregnancy from taking hold. Does not respond to ovielixirs.
    WORM_STUFFED = "Worm Stuffed"
}
