import { SpriteName } from './SpriteName';
import { Dictionary } from '../Engine/Utilities/Dictionary';

const dir = "resource/sprites/";

export const SpriteLib = new Dictionary<SpriteName, string>();
SpriteLib.set(SpriteName.Akbal, dir + "akbal.png");
SpriteLib.set(SpriteName.Amarok, dir + "amarok.png");
SpriteLib.set(SpriteName.Amily, dir + "amily defurr.png");
SpriteLib.set(SpriteName.Amily_Defurr, dir + "amily.png");
SpriteLib.set(SpriteName.Anemone, dir + "anemone.png");
SpriteLib.set(SpriteName.Arian, dir + "arian.png");
SpriteLib.set(SpriteName.Basilisk, dir + "basilisk.png");
SpriteLib.set(SpriteName.BeeGirl, dir + "bee girl.png");
SpriteLib.set(SpriteName.Ceraph, dir + "ceraph clothed.png");
SpriteLib.set(SpriteName.Ceraph_Clothed, dir + "ceraph goblin.png");
SpriteLib.set(SpriteName.Ceraph_Goblin, dir + "ceraph.png");
SpriteLib.set(SpriteName.Cerulean_Succubus, dir + "cerulean succubus.png");
SpriteLib.set(SpriteName.ChameleonGirl, dir + "chameleon.png");
SpriteLib.set(SpriteName.Chicken_Harpy, dir + "chicken harpy.png");
SpriteLib.set(SpriteName.Chilly_Smith, dir + "chilly smith.png");
SpriteLib.set(SpriteName.Christmas_Elf, dir + "christmas elf.png");
SpriteLib.set(SpriteName.Cinnabar, dir + "cinnabar.png");
SpriteLib.set(SpriteName.Corrupted_Glade, dir + "corrupted glade.png");
SpriteLib.set(SpriteName.Cotton, dir + "cotton.png");
SpriteLib.set(SpriteName.Cumwitch, dir + "cumwitch.png");
SpriteLib.set(SpriteName.Dickworms, dir + "dickworms.png");
SpriteLib.set(SpriteName.Dominika_Cloaked, dir + "dominika cloaked.png");
SpriteLib.set(SpriteName.Dominika_Uncloaked, dir + "dominika uncloaked.png");
SpriteLib.set(SpriteName.Drider, dir + "drider.png");
SpriteLib.set(SpriteName.Easter_Bunny, dir + "easter bunny.png");
SpriteLib.set(SpriteName.Edryn, dir + "edryn.png");
SpriteLib.set(SpriteName.Exgartuan, dir + "exgartuan.png");
SpriteLib.set(SpriteName.Factory_Omnibus, dir + "factory omnibus.png");
SpriteLib.set(SpriteName.Faerie, dir + "faerie.png");
SpriteLib.set(SpriteName.Fen_Imp, dir + "fenimp.png");
SpriteLib.set(SpriteName.Fetish_Cultist, dir + "fetish cultist.png");
SpriteLib.set(SpriteName.Fetish_Zealot, dir + "fetish zealot.png");
SpriteLib.set(SpriteName.Giacomo, dir + "giacomo.png");
SpriteLib.set(SpriteName.Goblin, dir + "goblin elder.png");
SpriteLib.set(SpriteName.Goblin_Elder, dir + "goblin shaman.png");
SpriteLib.set(SpriteName.Goblin_Shaman, dir + "goblin warrior.png");
SpriteLib.set(SpriteName.Goblin_Warrior, dir + "goblin.png");
SpriteLib.set(SpriteName.Goo_Girl, dir + "goo girl.png");
SpriteLib.set(SpriteName.Gnoll_Club, dir + "club gnoll.png");
SpriteLib.set(SpriteName.Gnoll_Spear, dir + "spear gnoll.png");
SpriteLib.set(SpriteName.Greenslime, dir + "green slime.png");
SpriteLib.set(SpriteName.Harpy, dir + "harpy.png");
SpriteLib.set(SpriteName.Hel, dir + "hel.png");
SpriteLib.set(SpriteName.Hel_BB, dir + "hel BB.png");
SpriteLib.set(SpriteName.Hel_BB_PF, dir + "hel BB PF.png");
SpriteLib.set(SpriteName.Hel_PF, dir + "hel PF.png");
SpriteLib.set(SpriteName.Hel2, dir + "hel2.png");
SpriteLib.set(SpriteName.Hellhound, dir + "hellhound.png");
SpriteLib.set(SpriteName.Ifris, dir + "ifris.png");
SpriteLib.set(SpriteName.Imp, dir + "imp.png");
SpriteLib.set(SpriteName.Imp_Overlord, dir + "imp overlord.png");
SpriteLib.set(SpriteName.Imp_Warlord, dir + "imp warlord.png");
SpriteLib.set(SpriteName.Incubus_Mechanic, dir + "incubus mechanic.png");
SpriteLib.set(SpriteName.Isabella, dir + "isabella.png");
SpriteLib.set(SpriteName.Izma, dir + "izma.png");
SpriteLib.set(SpriteName.Jasun, dir + "jasun.png");
SpriteLib.set(SpriteName.Jojo, dir + "jojo tentacle.png");
SpriteLib.set(SpriteName.Jojo_Tentacle, dir + "jojo.png");
SpriteLib.set(SpriteName.Katherine, dir + "katherine.png");
SpriteLib.set(SpriteName.Kelt, dir + "kelt.png");
SpriteLib.set(SpriteName.Kid_A, dir + "kida.png");
SpriteLib.set(SpriteName.Kiha, dir + "kiha.png");
SpriteLib.set(SpriteName.Kitsune_Black, dir + "kitsune black.png");
SpriteLib.set(SpriteName.Kitsune_Blonde, dir + "kitsune blonde.png");
SpriteLib.set(SpriteName.Kitsune_Red, dir + "kitsune red.png");
SpriteLib.set(SpriteName.Lilium, dir + "lilium.png");
SpriteLib.set(SpriteName.Lottie, dir + "lottie.png");
SpriteLib.set(SpriteName.Lumi, dir + "lumi.png");
SpriteLib.set(SpriteName.Lynette, dir + "lynette.png");
SpriteLib.set(SpriteName.Maddie, dir + "maddie.png");
SpriteLib.set(SpriteName.Marae, dir + "marae.png");
SpriteLib.set(SpriteName.Marble, dir + "marble.png");
SpriteLib.set(SpriteName.Markus_and_Lucia, dir + "markus and lucia.png");
SpriteLib.set(SpriteName.Minerva_Corrupt, dir + "minerva corrupt.png");
SpriteLib.set(SpriteName.Minerva_Pure, dir + "minerva pure.png");
SpriteLib.set(SpriteName.Minerva, dir + "minerva.png");
SpriteLib.set(SpriteName.Minotaur, dir + "minotaur sons.png");
SpriteLib.set(SpriteName.Minotaur_Sons, dir + "minotaur.png");
SpriteLib.set(SpriteName.Mrs_Coffee, dir + "mrs coffee.png");
SpriteLib.set(SpriteName.Naga, dir + "naga.png");
SpriteLib.set(SpriteName.Oasis_Demons, dir + "oasis demons.png");
SpriteLib.set(SpriteName.Oswald, dir + "oswald.png");
SpriteLib.set(SpriteName.Poisontail, dir + "poisontail.png");
SpriteLib.set(SpriteName.Priscilla, dir + "priscilla.png");
SpriteLib.set(SpriteName.Rathazul, dir + "rathazul.png");
SpriteLib.set(SpriteName.Rogar, dir + "rogar.png");
SpriteLib.set(SpriteName.Rubi_Hornless, dir + "rubi hornless.png");
SpriteLib.set(SpriteName.Rubi_Horns, dir + "rubi horns.png");
SpriteLib.set(SpriteName.SandTrap, dir + "sandtrap.png");
SpriteLib.set(SpriteName.SandWitch, dir + "sandwich.png");
SpriteLib.set(SpriteName.Satyr, dir + "satyr.png");
SpriteLib.set(SpriteName.Scylla, dir + "scylla and bear.png");
SpriteLib.set(SpriteName.Scylla_And_Bear, dir + "scylla.png");
SpriteLib.set(SpriteName.Sean, dir + "sean.png");
SpriteLib.set(SpriteName.Sharkgirl, dir + "sharkgirl.png");
SpriteLib.set(SpriteName.Sophie, dir + "sophie.png");
SpriteLib.set(SpriteName.Sophie_Bimbo, dir + "sophie bimbo.png");
SpriteLib.set(SpriteName.Spidergirl, dir + "spidergirl.png");
SpriteLib.set(SpriteName.Spiderguy, dir + "spiderguy.png");
SpriteLib.set(SpriteName.Stuck_Satyr, dir + "stuck satyr.png");
SpriteLib.set(SpriteName.Succubus_Secretary, dir + "succubus secretary.png");
SpriteLib.set(SpriteName.Tamani_Daughters, dir + "tamani daughters.png");
SpriteLib.set(SpriteName.Tamani, dir + "tamani.png");
SpriteLib.set(SpriteName.TentacleBeast, dir + "tentacle monster.png");
SpriteLib.set(SpriteName.Urta, dir + "urta drunk.png");
SpriteLib.set(SpriteName.Urta_Drunk, dir + "urta.png");
SpriteLib.set(SpriteName.Vagrant_Cats, dir + "vagrant cats.png");
SpriteLib.set(SpriteName.Vala, dir + "vala slave.png");
SpriteLib.set(SpriteName.Vala_Slave, dir + "vala.png");
SpriteLib.set(SpriteName.Valeria, dir + "valeria.png");
SpriteLib.set(SpriteName.Venus, dir + "venus.png");
SpriteLib.set(SpriteName.Victoria, dir + "victoria.png");
SpriteLib.set(SpriteName.Weaponsmith, dir + "weaponsmith.png");
SpriteLib.set(SpriteName.Yara, dir + "yara.png");
SpriteLib.set(SpriteName.Yvonne, dir + "yvonne.png");
